### ISSUE TITLE
Раздел 3-directives  подраздел 1-categories-menu-component

### ISSUE THREAD

**Issue by mahmudka** [NepipenkoIgor/project-ngx-shop-task-book#10]
В разделе 3-directives в первом подразделе  в документе README.md  неверные скрипты 
Должно быть:
npm start -- 3-directives_1-categories-menu-component
npm run test -- 3-directives_1-categories-menu-component
npm run lint -- 3-directives_1-categories-menu-component
А сейчас есть:
npm run start:3-directives_1-transforms-with-pipe
npm run test:3-directives_1-transforms-with-pipe
npm run lint:3-directives_1-transforms-with-pipe

**Comment by NepipenkoIgor** [comment]
@mahmudka  Done
