### ISSUE TITLE
Задание 3 - directives часть 3-information-component

### ISSUE THREAD

**Issue by jeennick** [NepipenkoIgor/project-ngx-shop-task-book#16]
Не могу пройти тесты, даже пробовал просто скопировать решение из solution, всё равно ловится ошибка:

Chrome Headless 85.0.4183.121 (Windows 10) [Moдуль 3 - Компонент информации о товаре] тег с селектором .rate-amount  должен правильно интерполировать свойство feedbacksCount продукта 
FAILED
        Error: Expected '2 отзыва' to equal '2 отзывa'.

**Comment by NepipenkoIgor** [comment]
@jeennick  Спасибо , поправил. Ошибка была в строках при сравнении
