### ISSUE TITLE
Дублирование тест кейса

### ISSUE THREAD

**Issue by wwwtsv** [NepipenkoIgor/project-ngx-shop-task-book#26]
https://github.com/NepipenkoIgor/project-ngx-shop-task-book/blob/master/1-components/1-shop-card/src/app/shop-card/shop-card.component.spec.ts#L38 - вот этот тест из строки 38 полностью дублирует тест из строки 29 этого же файла
https://github.com/NepipenkoIgor/project-ngx-shop-task-book/blob/master/1-components/1-shop-card/src/app/shop-card/shop-card.component.spec.ts#L29

```
it('компонент должен иметь cобственное событие increment ', () => {
    expect((component as any).increment).toBeTruthy();
    expect((component as any).increment).toBeInstanceOf(EventEmitter);
  });
```

**Comment by NepipenkoIgor** [comment]
Спасибо , @wwwtsv   посмотрю
