### ISSUE TITLE
Авто-тесты в разделе 2-pipe

### ISSUE THREAD

**Issue by aleshkinpaul** [NepipenkoIgor/project-ngx-shop-task-book#33]
Добрый день!

В тестах: project-ngx-shop-task-book/2-pipe/1-transforms-with-pipe/src/app/pipes/review.pipe.spec.ts
Выполняется проверка значений, не соответствующих ожидаемому результату
Для количества отзывов 11 ожидается строка "2 отзыва"

 
```
it('Eсли значение к которому применяется pipe число заканчиваеться на 2 - 4  pipe должен возвращать "${count} отзыва"', () =&gt; {    
    expect(reviewPipe.transform(11)).toEqual('2 отзыва');    
    expect(reviewPipe.transform(12)).toEqual('34 отзыва');    
    expect(reviewPipe.transform(13)).toEqual('44 отзыва');    
    expect(reviewPipe.transform(14)).toEqual('93 отзыва');  
});
```

**Comment by aleshkinpaul** [comment]
Во всех последующих тестах, где выполняются проверки пайпа количества отзывов, эта ошибка также повторяется

**Comment by NepipenkoIgor** [comment]
Fixed
