### ISSUE TITLE
2-pipe/1-transforms-with-pipe contains test case error

### ISSUE THREAD

**Issue by VictorZubr** [NepipenkoIgor/project-ngx-shop-task-book#39]
2-pipe/1-transforms-with-pipe/src/app/pipes/review.pipe.spec.ts contain test case error in line [34](https://github.com/NepipenkoIgor/project-ngx-shop-task-book/blob/master/2-pipe/1-transforms-with-pipe/src/app/pipes/review.pipe.spec.ts#L34)

**Comment by NepipenkoIgor** [comment]
@VictorZubr  Merged
