### ISSUE TITLE
Task 3_1 categories-menu слетели стили меню категорий

### ISSUE THREAD

**Issue by Bullettime23** [NepipenkoIgor/project-ngx-shop-task-book#44]
![image](https://user-images.githubusercontent.com/51997061/135760959-cb98841f-745c-4bde-90c0-23cefdb4aa3c.png)
VS 
![image](https://user-images.githubusercontent.com/51997061/135761068-bf84ae6f-3f12-4c7a-855a-1a754f7c02f8.png)

**Comment by NepipenkoIgor** [comment]
@Bullettime23  Поправил , посмотрите. Так же обратите внимание, что нужно переинсталить зависимости. Они обновлены.
