### ISSUE TITLE
4-services/1-home-page Property 'items' does not exist on type 'IProduct[]'

### ISSUE THREAD

**Issue by viartemyeva** [NepipenkoIgor/project-ngx-shop-task-book#47]
Подскажите пж-та по ДЗ 4-services/1-home-page. Если в компонент ngx-shop-home-page передаю в инпут результат запроса так: [products]="products$ | async", то падает на перечислении по внутреннему *ngFor (см. скрин). В решении предлагается другая форма: [products]="(products$ | async)?.items" , но при ее использовании возникает ошибка компиляции Property 'items' does not exist on type 'IProduct[]' (см. скрин).

![image](https://user-images.githubusercontent.com/92302216/142658436-1b7616e3-8ce3-4a23-9d14-66be7f826243.png)
![image](https://user-images.githubusercontent.com/92302216/142658476-ae083ec6-fa16-4d33-b959-13d2bd43282a.png)
![image](https://user-images.githubusercontent.com/92302216/142658514-38ceef78-bc00-404c-88c4-ebffb782b838.png)

**Comment by NepipenkoIgor** [comment]
Поправил , посмотрите. Так же обратите внимание, что нужно переинсталить зависимости. Они обновлены.
