### ISSUE TITLE
сообщение об ошибке в тесте 1-components_1-shop-card

### ISSUE THREAD

**Issue by jeennick** [NepipenkoIgor/project-ngx-shop-task-book#5]
При выполнении тестов 
`npm run test:1-components_1-shop-card`
заметил странную ошибку:
`Chrome Headless 85.0.4183.83 (Windows 10) [Moдуль 1 -  Компонент товара в корзин] тег с селектором .product-desc span.rate-amount  должен правильно интерполировать свойство name продукта FAILED`
непонятно, почему говорится про свойство name, если речь о поле .rate-amount.

**Comment by NepipenkoIgor** [comment]
Done
